apiVersion: apps/v1
kind: Deployment
metadata:
  name: "labeling-api-redis"
  labels:
    app: "labeling-api-redis"
spec:
  selector:
    matchLabels:
      app: "labeling-api-redis"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "labeling-api-redis"
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: "redis"
spec:
  selector:
    app: "labeling-api-redis"
  type: ClusterIP
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379