apiVersion: v1
kind: Service
metadata:
  name: 'starter-api-service'
spec:
  selector:
    app: 'starter-api'
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
